server-type: LOBBY

ignore-events: []

threads: 1

lobby: "lobby"

arena-list:
  title: "Список арен"
  item:
    material: PAPER
    name: "Арена"
    lore:
      - "%all/%max"
      - "Надо %need"

servers:
  a:
    name: "Какая-то карта"
    need: 3
    max: 8
    server: a